defmodule Mix.Tasks.Spec.Init do
  use Mix.Task

  @shortdoc "Scaffolds a canonical .spec/ workspace"

  @readme_template """
  # `.spec`

  This folder is the package-local Spec Led layer.

  ## Canonical Layout

  - `README.md` (authored)
  - `specs/spec_system.spec.md` (authored, meta-spec for this folder)
  - `specs/package.spec.md` (authored, package-level intent)
  - `specs/*.spec.md` (authored subject specs)
  - `state.json` (generated by `mix spec.plan` and `mix spec.verify`)

  ## Core Loop

  1. define intent
  2. build code/docs/tests
  3. run `mix spec.check`
  """

  @spec_system_template """
  # Spec System

  This subject defines the contract for the `.spec` workspace itself.

  ```spec-meta
  id: spec.system
  kind: policy
  status: active
  summary: Canonical workspace contract for authored specs and generated Spec Led state.
  surface:
    - .spec/README.md
    - .spec/specs/*.spec.md
    - .spec/state.json
  ```

  ## Requirements

  ```spec-requirements
  - id: spec.workspace.readme_present
    statement: The repository shall include a .spec/README.md that explains purpose, layout, and workflow.
    priority: must
    stability: stable

  - id: spec.workspace.state_generated
    statement: When planning and verification run, the workspace shall generate .spec/state.json containing index and verification state.
    priority: must
    stability: stable
  ```

  ## Verification

  ```spec-verification
  - kind: source_file
    target: .spec/README.md
    covers:
      - spec.workspace.readme_present

  - kind: command
    target: mix spec.plan
    covers:
      - spec.workspace.state_generated

  - kind: command
    target: mix spec.verify
    covers:
      - spec.workspace.state_generated
  ```
  """

  @package_template """
  # Package

  High-level package contract.

  ```spec-meta
  id: package.todo
  kind: package
  status: active
  summary: Package-level specification.
  surface: []
  ```

  ## Requirements

  ```spec-requirements
  - id: package.todo.requirement
    statement: Define package behavior requirements here.
    priority: must
    stability: evolving
  ```

  ## Exceptions

  ```spec-exceptions
  - id: package.todo.bootstrap_waiver
    covers:
      - package.todo.requirement
    reason: Starter scaffold leaves package-specific requirements for the author to refine.
  ```
  """

  @impl true
  def run(args) do
    Mix.Task.run("app.start")

    {opts, rest, invalid} =
      OptionParser.parse(args,
        strict: [root: :string, force: :boolean],
        aliases: [r: :root, f: :force]
      )

    validate_args!(rest, invalid)

    root = opts[:root] || File.cwd!()
    force? = opts[:force] || false
    spec_dir = Path.join(root, ".spec")
    specs_dir = Path.join(spec_dir, "specs")

    File.mkdir_p!(spec_dir)
    File.mkdir_p!(specs_dir)

    write_template(Path.join(spec_dir, "README.md"), @readme_template, force?)
    write_template(Path.join(specs_dir, "spec_system.spec.md"), @spec_system_template, force?)
    write_template(Path.join(specs_dir, "package.spec.md"), @package_template, force?)

    Mix.shell().info("spec.init scaffolded #{spec_dir}")
  end

  defp write_template(path, content, force?) do
    cond do
      force? ->
        File.write!(path, content)
        Mix.shell().info("wrote #{path}")

      File.exists?(path) ->
        Mix.shell().info("kept #{path}")

      true ->
        File.write!(path, content)
        Mix.shell().info("wrote #{path}")
    end
  end

  defp validate_args!([], []), do: :ok

  defp validate_args!(rest, invalid) do
    invalid_flags = Enum.map(invalid, fn {flag, _value} -> flag end)
    extra_args = Enum.map(rest, &inspect/1)
    details = Enum.join(invalid_flags ++ extra_args, ", ")
    Mix.raise("Invalid arguments for spec.init: #{details}")
  end
end
